// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRxU8T2cF6G7dIsvG1gZawGrE0abXsQGc',
    appId: '1:560696576076:web:6240a9f98adbd4eddc0ce9',
    messagingSenderId: '560696576076',
    projectId: 'medapp-a65c6',
    authDomain: 'medapp-a65c6.firebaseapp.com',
    storageBucket: 'medapp-a65c6.firebasestorage.app',
    measurementId: 'G-BLB14SBBGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRWCLEiwrDnUcN_vRTjHeBLFe-iOXtCsY',
    appId: '1:560696576076:android:3b1b71a7ebd00b9fdc0ce9',
    messagingSenderId: '560696576076',
    projectId: 'medapp-a65c6',
    storageBucket: 'medapp-a65c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGg4n-Vbus6YZV-JEoGNcVkqWZiI9IGrU',
    appId: '1:560696576076:ios:8ebdb3a2a8c6b448dc0ce9',
    messagingSenderId: '560696576076',
    projectId: 'medapp-a65c6',
    storageBucket: 'medapp-a65c6.firebasestorage.app',
    iosBundleId: 'com.example.medapp',
  );
}
